version: '3.1'
services:
  stats-db:
    container_name: ewmstat_db
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_DB=ewmstat
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  stats-server:
    container_name: ewmstat_server
    build: stat/service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - STAT_SERVICE_PORT=9090
      - DB_NAME=ewmstat
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=stats-db
      - DB_PORT=5432

  ewm-db:
    container_name: ewmmain_db
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewmmain
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    container_name: ewmmain_server
    build: main
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - MAIN_PORT=8080
      - DB_NAME=ewmmain
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=ewm-db
      - DB_PORT=5432
      - STAT_SERVICE_URL=http://stats-server:9090