version: '3.1'
services:
  stats-db:
    container_name: ewmstat_db
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewmstat
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  stats-server:
    container_name: ewmstat_server
    build: stat/service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - STAT_SERVICE_PORT=9090
      - DB_NAME=ewmstat
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=stats-db
      - DB_PORT=5432

#  ewm-service:
#    ports:
#      - "8080:8080"

#  ewm-db:
#    image: postgres:14-alpine